name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      
    - name: Restore dependencies
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        cd ./M220N
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        docker build -t $APP_NAME .
        docker run -p 80:80 $APP_NAME
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
